"""created a profile table

Revision ID: 81938d45e78c
Revises: d9eb8d4f33d3
Create Date: 2024-10-02 09:45:58.415755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81938d45e78c'
down_revision = 'd9eb8d4f33d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    # ### end Alembic commands ###
